### ISSUE TITLE
Image doesnt refresh when uri change

### ISSUE THREAD

**Issue by MagicMirouff** [code-and-co/react-native-image-offline#1]
HI,
I have to update the source of my image. Here what i do
  <OfflineImage
                        resizeMode={'cover'}
                          style={{
                                flex: 1,
                                width: Dimensions.get('window').width / 2
                              }}
                          source={ { uri: data.main_image[this.state.selectImagePosition] }}

But the image doesnt change. Any idea ?

**Comment by MagicMirouff** [comment]
ADDED This in OfflineImage and it seems to work well

componentWillReceiveProps(nextProps) {
      const nextSource = nextProps.source;
      const reloadImage = nextProps.reloadImage;
      const source = this.props.source;
      if (nextSource !== source){
        const offlinePath = offlineImageStore.getImageOfflinePath(nextSource.uri);
        this.setState({ path: offlinePath });
        //offlineImageStore.subscribe(source, this.handler, reloadImage);
      }
  }

**Comment by codeandco-jay** [comment]
Thanks for adding the issue and fix it :) I have added it and should in 0.0.8 version.

**Comment by MagicMirouff** [comment]
No problem.

You did great work with this lib ^^

**Comment by airTradies** [comment]
This still seems to be an issue on 0.1.4. We are changing the uri of the image, but it does not reload. I have checked OfflineImage.js and the code changes listed above are there, although 1 line is different....

 if (nextSource && source && nextSource.uri !== source.uri){

I put some logging before that if statement and noticed that nextSource.uri and source.uri are showing as the same value, even though I change the value
