### ISSUE TITLE
when image url is empty, fallback source doesnt seem to work

### ISSUE THREAD

**Issue by vijayalakshmiin** [code-and-co/react-native-image-offline#10]
<OfflineImage
            accessibilityLabel="logo"
            accesible
            key={KEY_COMMON_EYE_CLOSE}
            style={styles.eyeIcon}
            reloadImage
            fallbackSource={this.state.eye}
            source={{
              uri: "",
            }}
          />

When uri value is empty, it doesnt seem to load the fallback source. How to do this. Please let me know

**Comment by jjayasagar** [comment]
Thanks for creating the issue!

Seems like, at the moment, `source.uri` cannot be empty!  

I am working on it! Meanwhile, you can make sure `source.uri` not empty. Example:
`<OfflineImage
                        key={'https://wrong-url/noImageExist.jpg'}
                        resizeMode={'center'}
                        style={ { width: '99%', height: 110, margin: 5 } }
                        fallbackSource={ Images.fallbackSource }
                        source={ { uri: 'https://wrong-url/noImageExist.jpg' } }/>`

**Comment by vijayalakshmiin** [comment]
Sure. Thank you. Also, Please let me know how to handle onclick on OfflineImage ?
