### ISSUE TITLE
Push code for v0.0.7

### ISSUE THREAD

**Issue by stigi** [code-and-co/react-native-image-offline#2]
I notices that the version that is released via [npm](https://www.npmjs.com/package/react-native-image-offline) is `v0.0.7` and is ahead of `v0.0.6` which is the most current in this repo.

Can you push the changes to GitHub as I would like to send a merge request against the most recent state?

Thanks

**Comment by codeandco-jay** [comment]
Sorry for late response, I will push today! Thanks for the request :)
