### ISSUE TITLE
React native 0.59 Async storage

### ISSUE THREAD

**Issue by horaciomoreno10** [code-and-co/react-native-image-offline#22]
After update react native to 0.59, I found some warnings related to AsyncStorage, because, the lastest version of react native, dont use AsyncStorage from react-native, they has moved this dependency to https://github.com/react-native-community/react-native-async-storage , I ask me if is possible do this change, if you want i could make a pull request with this change

**Comment by BHesseldieck** [comment]
will be fixed in the next version

**Comment by Amit1405** [comment]
Hii 
Async storage not working .. it shows failed to download this image 
Please help .. how to implement with async storage
