### ISSUE TITLE
Corrupted Images on first load

### ISSUE THREAD

**Issue by uncledent** [code-and-co/react-native-image-offline#7]
When I install the app and fetch news with images, it stays a fallback image for several seconds and then the image appears corrupted:

<img width="349" alt="screen shot 2018-05-02 at 22 57 06" src="https://user-images.githubusercontent.com/6542981/39548953-6dbeef40-4e5c-11e8-9d43-76bb55a2041f.png">

What direction should I keep digging? 

The lib is great! Thank you!

**Comment by jjayasagar** [comment]
Hi @uncledent 

Thanks for writing the issue! 

This issue is not related to the library :) We also face it sometimes depending network issues.

Waiting to get an update from RN fetch blob library. Refer here
Related issue: https://github.com/wkh237/react-native-fetch-blob/issues/622
Old Repo: https://github.com/wkh237/react-native-fetch-blob/issues
New repo: https://github.com/joltup/react-native-fetch-blob

Take a look and try to get some more information.

I will try to update this dependency ASAP.

**Comment by uncledent** [comment]
Thank you for your answer, @jjayasagar. Maybe we could do some temporary workaround? For example render/load image twice on first load or something like this?

**Comment by jjayasagar** [comment]
Maybe we could try, however, not on the master branch!! You could try it on a forked repository and use it in your code :)

Thanks!

**Comment by uncledent** [comment]
A quick workaround for this issue is to rerender the image when it is loaded, like this:

``` 
onloadEnd() {
        // rerender image
        this.setState({ renderCount: 1 })
}

<OfflineImage
            key={src.uri + this.state.renderCount}
            source={src}
            onLoadEnd={this.onloadEnd}
            {...this.props}
  />
```
This is ugly, but less ugly as corrupted images.

**Comment by jjayasagar** [comment]
Thanks @uncledent I will quickly and let you know.

**Comment by jjayasagar** [comment]
Now you can use `onLoadEnd` param 

`<OfflineImage
          key={'https://wallpaperbrowse.com/media/images/wallpaper-for-mobile-13.jpg'}
          onLoadEnd={(sourceUri) => {
            console.log('Loading finished for image with path: ', sourceUri)
          }}
          reloadImage = { true }
          resizeMode={'cover'}
          fallbackSource={ Images.fallbackSource }
          style={ { width: '99%', height: 110, margin: 5 } }
          source={ { uri: 'https://wallpaperbrowse.com/media/images/wallpaper-for-mobile-13.jpg' } }/>` 

Please try and let me know if it helps! Thanks!!

**Comment by uncledent** [comment]
Unfortunately the issue is still there, workaround helps sometimes but not always. And it adds ugly flickering of the image :( Can anyone think of some better workaround for this?

**Comment by jjayasagar** [comment]
That's true @uncledent. It has to be fixed in the `rn-fetch-blob`.

**Comment by uncledent** [comment]
@jjayasagar i think this may be caused by the situation that we try to show the image right after it was downloaded by rn-fetch-blob, but at that time it is not fully saved to the file system. I try to add a small timeout before updating state of the component, it seems to work. I will do some more investigation on this.

**Comment by jjayasagar** [comment]
@uncledent  Thank you for taking time and putting the efforts. Would be really nice to your thoughts 👍

**Comment by OpenSpryMatt** [comment]
@uncledent How did you implement this short timeout? This is really annoying us. The correct image even loads for the first second, then is drawn over by the half grey/green image.

**Comment by loismeira** [comment]
Hi, what are the latest news on this issue? We have encountered it with expo-file-system downloadAsync.

**Comment by Jayasagar** [comment]
Hi @loismeira This repo is no longer maintained! Sorry for that.
